// <auto-generated />
namespace HucaresServer.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LicensePlateFoundStatusEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LicensePlateFoundStatusEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201810241343186_LicensePlateFoundStatusEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
